system:
  name: ADMF-Trader-MVP
  version: 0.1.0
logging:
  level: DEBUG
components:
  dummy_service:
    some_setting: Dummy setting
  ensemble_strategy:
    symbol: SPY
    short_window_default: 10
    long_window_default: 20
    ma_rule.weight: 0.2
    short_window: 5
    long_window: 20
    rsi_indicator:
      period: 20
    rsi_rule:
      oversold_threshold: 20.0
      overbought_threshold: 80.0
      weight: 0.8
    rsi_rule.weight: 0.8
  regime_adaptive_strategy:
    symbol: SPY
    short_window_default: 10
    long_window_default: 20
    ma_rule.weight: 0.6
    regime_detector_service_name: MyPrimaryRegimeDetector
    regime_params_file_path: regime_optimized_parameters.json
    fallback_to_overall_best: true
  data_handler_csv:
    csv_file_path: data/SPY_1min.csv
    symbol: SPY
    timestamp_column: timestamp
    train_test_split_ratio: 0.8
    open_column: Open
    high_column: High
    low_column: Low
    close_column: Close
    volume_column: Volume
  basic_portfolio:
    initial_cash: 100000.0
  basic_risk_manager:
    target_trade_quantity: 100
  simulated_execution_handler:
    default_quantity: 100
    commission_per_trade: 0.005
    commission_type: per_share
    passthrough: false
    fill_price_logic: signal_price
  optimizer:
    strategy_service_name: strategy
    portfolio_service_name: portfolio_manager
    data_handler_service_name: data_handler
    risk_manager_service_name: risk_manager
    execution_handler_service_name: execution_handler
    metric_to_optimize: get_final_portfolio_value
    higher_metric_is_better: true
    min_trades_per_regime: 2
    regime_metric: sharpe_ratio
    output_file_path: regime_optimized_parameters.json
    top_n_to_test: 3
    clear_regime_performance: true
  MyPrimaryRegimeDetector:
    min_regime_duration: 2
    verbose_logging: false
    summary_interval: 50
    indicators:
      rsi_14:
        type: rsi
        parameters:
          period: 14
      atr_20:
        type: atr
        parameters:
          period: 10
      trend_10_30:
        type: simple_ma_trend
        parameters:
          short_period: 5
          long_period: 20
    regime_thresholds:
      trending_up_volatile:
        trend_10_30:
          min: 0.02
        atr_20:
          min: 0.15
      trending_up_low_vol:
        trend_10_30:
          min: 0.02
        atr_20:
          max: 0.15
      ranging_low_vol:
        trend_10_30:
          min: -0.01
          max: 0.01
        atr_20:
          max: 0.12
      trending_down:
        trend_10_30:
          max: -0.01
      oversold_in_uptrend:
        rsi_14:
          max: 40
        trend_10_30:
          min: 0.01
