# Test configuration for optimization
run_mode: optimization

# Optimization configuration
optimization:
  strategy_name: strategy  # Name of strategy component to optimize
  method: grid            # Optimization method: grid, random
  metric: sharpe_ratio    # Metric to optimize: sharpe_ratio, total_return, max_drawdown
  results_dir: optimization_results
  regime_specific: true   # Enable regime-specific optimization
  regimes: ['trending_up', 'trending_down', 'volatile', 'default']  # Regimes to optimize
  
  # Optional: limit iterations for testing
  n_iterations: 20        # For random search

# Components configuration
components:
  # Data handler
  data_handler:
    class_path: src.data.csv_data_handler.CSVDataHandler
    config:
      csv_file_path: data/SPY_1min.csv
      symbol: SPY
      # bars_limit: 1000  # Comment out for full data
      train_test_split_ratio: 0.8  # Use 80% for training

  # Strategy - using the new composite architecture
  strategy:
    class_path: src.strategy.implementations.composite_ma_strategy.CompositeMAStrategy
    config:
      fast_ma_period: 10
      slow_ma_period: 20
      use_rsi_filter: false  # Start simple
      aggregation_method: weighted

  # Portfolio manager
  portfolio_manager:
    class_path: src.risk.basic_portfolio.BasicPortfolio
    config:
      initial_cash: 100000

  # Risk manager
  risk_manager:
    class_path: src.risk.basic_risk_manager.BasicRiskManager
    config:
      target_trade_quantity: 100
      portfolio_manager_key: portfolio_manager

  # Regime detector
  regime_detector:
    class_path: src.strategy.regime_detector.RegimeDetector
    config:
      regime_thresholds:
        trending_up:
          ma_trend:
            min: 0.01  # Changed from 0.7 to 0.01 (1% trend strength)
          rsi:
            min: 55
            max: 80
        trending_down:
          ma_trend:
            max: -0.01  # Changed from -0.7 to -0.01 (-1% trend strength)
          rsi:
            min: 20
            max: 45
        volatile:
          atr:
            min: 0.5  # Changed from 0.015 to 0.5 (much higher threshold)
      min_regime_duration: 5
      indicators:
        ma_trend:
          type: simple_ma_trend
          parameters:
            short_window: 10
            long_window: 30
        rsi:
          type: rsi
          parameters:
            period: 14
        atr:
          type: atr
          parameters:
            period: 14

  # Execution handler
  execution_handler:
    class_path: src.execution.simulated_execution_handler.SimulatedExecutionHandler
    config:
      default_quantity: 100
      commission: 0.005
      passthrough: false

  # Backtest runner (used by optimization)
  backtest_runner:
    class_path: src.execution.backtest_runner.BacktestRunner
    config:
      use_test_dataset: false  # Use training data during optimization
      close_positions_at_end: true

  # Optimizer component (named 'optimizer' as expected by Bootstrap)
  optimizer:
    class_path: src.execution.optimization_entrypoint.OptimizationEntrypoint
    config:
      strategy_name: strategy
      method: grid
      metric: sharpe_ratio
      regime_specific: true
      regimes: ['trending_up', 'trending_down', 'volatile', 'default']

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"