# Configuration for debugging OOS vs Production discrepancies
# Based on config_production.yaml with debug logging enabled

# Core settings
data_path: "data/1000_1min.csv"
symbol: "SPY"
initial_cash: 100000.0
risk_per_trade: 0.02  # 2% risk per trade
backtest_mode: true  # Enable backtest mode

# Component configurations
components:
  # Data Handler configuration
  data_handler_csv:
    csv_file_path: "data/1000_1min.csv"
    symbol: "SPY"
    train_ratio: 0.8
    
  # Portfolio Manager configuration  
  portfolio_manager:
    initial_cash: 100000.0
    
  # Risk Manager configuration
  risk_manager:
    risk_per_trade: 0.02
    max_portfolio_risk: 0.06
    max_position_count: 3
    
  # Execution Handler configuration
  execution_handler:
    slippage_percent: 0.0
    commission_per_trade: 0.0
    
  # Regime Detector configuration with debug mode
  MyPrimaryRegimeDetector:
    type: "regime_detector"
    enabled: true
    debug_mode: true  # Enable enhanced debug logging
    min_regime_duration: 3
    indicators:
      ma_trend:
        type: simple_ma_trend
        parameters:
          short_period: 50
          long_period: 200
      atr:
        type: atr
        parameters:
          period: 20
      rsi:
        type: rsi
        parameters:
          period: 14
    regime_thresholds:
      trending_up:
        ma_trend:
          min: 0.5
        atr:
          min: 10
      trending_down:
        ma_trend:
          max: -0.5
        atr:
          min: 10
      ranging_high_vol:
        ma_trend:
          min: -0.5
          max: 0.5
        atr:
          min: 15
      ranging_low_vol:
        ma_trend:
          min: -0.5
          max: 0.5
        atr:
          max: 15
          
  # Strategy configuration
  ensemble_strategy:
    type: "ensemble_signal_strategy"
    enabled: true
    symbol: "SPY"
    parameters:
      ma_short_period: 20
      ma_long_period: 50
      rsi_period: 14
      bb_period: 20
      bb_std: 2.0
      rsi_oversold: 30
      rsi_overbought: 70
      volume_factor: 1.5
      ma_weight: 0.3
      rsi_weight: 0.3
      bb_weight: 0.2
      volume_weight: 0.2
      
  # Optimizer configuration
  optimizer:
    parameter_ranges:
      ma_short_period: [10, 30]
      ma_long_period: [40, 60]
      rsi_period: [10, 20]
      bb_period: [15, 25]
      bb_std: [1.5, 2.5]
      rsi_oversold: [20, 40]
      rsi_overbought: [60, 80]
      volume_factor: [1.0, 2.0]
      ma_weight: [0.1, 0.4]
      rsi_weight: [0.1, 0.4]
      bb_weight: [0.1, 0.3]
      volume_weight: [0.1, 0.3]
    train_ratio: 0.8
    metric: "sharpe_ratio"
    n_initial_samples: 50
    max_iterations: 10
    cv_splits: 3
    top_n_performers: 5

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/debug_comparison_{timestamp}.log"