# Unified configuration for both optimization and verification runs
# This single config can be used for:
# 1. Optimization: python main_ultimate.py --config config/config_unified_optimization_backtest.yaml --bars 10000 --optimize
# 2. Verification: python main_ultimate.py --config config/config_unified_optimization_backtest.yaml --bars 10000 --dataset test

# Core system configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Run mode - will be overridden by --optimize flag if present
run_mode: backtest

# Optimization configuration (used when --optimize flag is present)
optimization:
  strategy_name: strategy
  method: grid
  metric: sharpe_ratio
  max_iterations: 100
  regime_specific: true
  regimes: ["trending_up", "trending_down", "volatile", "default"]
  # Train/test split parameters
  optimization_method: "regime_specific_with_split"
  train_ratio: 0.8

# Component configurations
components:
  # Event bus
  event_bus:
    class_path: src.core.event_bus.EventBus
    config:
      name: "main_event_bus"

  # Data handler with train/test split support
  data_handler:
    class_path: src.data.csv_data_handler.CSVDataHandler
    config:
      csv_file_path: "data/SPY_1min.csv"
      symbol: "SPY"
      timestamp_column: "timestamp"
      # Train/test split ratio for both optimization and verification
      train_test_split_ratio: 0.8

  # Strategy configuration
  # When running optimization (--optimize), this will be optimized
  # When running verification (no --optimize), use RegimeAdaptiveStrategy for dynamic switching
  strategy:
    class_path: src.strategy.implementations.ensemble_strategy.EnsembleStrategy
    config:
      symbol: "SPY"
      # Base MA parameters
      ma_component:
        short_window: 10
        long_window: 20
        signal_threshold: 0.0001
      # RSI parameters
      rsi_component:
        period: 14
        oversold_threshold: 30
        overbought_threshold: 70
      # Parameter constraints for optimization
      parameter_constraints:
        ma_component.short_window:
          min: 5
          max: 15
          values: [5, 10, 15]
        ma_component.long_window:
          min: 20
          max: 40
          values: [20, 30, 40]
        rsi_component.period:
          min: 10
          max: 21
          values: [10, 14, 21]
        rsi_component.oversold_threshold:
          min: 20
          max: 40
          values: [20, 30, 40]
        rsi_component.overbought_threshold:
          min: 60
          max: 80
          values: [60, 70, 80]

  # Alternative strategy for verification with dynamic parameter switching
  # This component will be aliased as 'strategy' when NOT optimizing
  regime_adaptive_strategy:
    class_path: src.strategy.regime_adaptive_strategy.RegimeAdaptiveStrategy
    config:
      symbol: "SPY"
      # Path to optimized parameters (created by optimization run)
      regime_params_file_path: "regime_optimized_parameters.json"
      fallback_to_overall_best: true
      # Base parameters (will be overridden by regime-specific params from file)
      short_window: 10
      long_window: 20
      # RSI parameters
      use_rsi_filter: true
      rsi_period: 14
      rsi_oversold_threshold: 30
      rsi_overbought_threshold: 70
  
  # Optimizer entry point (only used when --optimize flag is present)
  optimizer:
    class_path: src.execution.optimization_entrypoint.OptimizationEntrypoint
    config:
      strategy_name: strategy
      method: grid
      metric: sharpe_ratio
      regime_specific: true
      optimization_method: "regime_specific_with_split"
      train_ratio: 0.8
      regimes: ["trending_up", "trending_down", "volatile", "default"]

  # Regime detector with indicators
  regime_detector:
    class_path: src.strategy.regime_detector.RegimeDetector
    config:
      min_regime_duration: 1
      indicators:
        ma_trend:
          type: simple_ma_trend
          parameters:
            short_period: 10
            long_period: 30
        rsi:
          type: rsi
          parameters:
            period: 14
        atr:
          type: atr
          parameters:
            period: 14
      regime_thresholds:
        trending_up:
          ma_trend:
            min: 0.01
          rsi:
            min: 55
            max: 80
        trending_down:
          ma_trend:
            max: -0.01
          rsi:
            min: 20
            max: 45
        volatile:
          atr:
            min: 0.5
        default:
          priority: 0

  # Risk management
  risk_manager:
    class_path: src.risk.basic_risk_manager.BasicRiskManager
    config:
      max_position_size: 100
      stop_loss_pct: 0.02

  # Portfolio management
  portfolio_manager:
    class_path: src.risk.basic_portfolio.BasicPortfolio
    config:
      initial_cash: 100000
      max_positions: 1

  # Execution handler
  execution_handler:
    class_path: src.execution.simulated_execution_handler.SimulatedExecutionHandler
    config:
      latency_ms: 10

  # Backtest runner
  backtest_runner:
    class_path: src.execution.backtest_runner.BacktestRunner
    config:
      start_date: "2024-01-01"
      end_date: "2024-12-31"
      # use_test_dataset is controlled by --dataset CLI flag