system:
  name: "ADMF-Trader-MVP"
  version: "0.1.0"

logging:
  level: "INFO" # Controls the logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

data: # This was an earlier placeholder, can be kept or removed if not directly used by main config loader
  csv_file_path: "data/SPY_1min.csv" 

components:
  dummy_service:
    some_setting: "Hello from DummyComponent in config!"
    another_setting: 42

  ma_crossover_strategy:
    symbol: "SPY" # Should match the symbol from CSVDataHandler
    short_window: 10 # Example: 10-period short MA
    long_window: 30  # Example: 30-period long MA

  # In config/config.yaml components section:
# In config/config.yaml components section:
  simulated_execution_handler:
    default_quantity: 100
    commission_per_trade: 0.005 # Example: 0.005 per share or a fixed $ amount
    commission_type: "per_share" # or "fixed_per_trade"
    passthrough: false 
    fill_price_logic: "signal_price" # Options: "signal_price", "next_bar_open" (more advanced)

  basic_portfolio:
    initial_cash: 100000.00

# In config/config.yaml, under components:
  basic_risk_manager:
    target_trade_quantity: 100 # Or your desired default

  optimizer:
    strategy_service_name: "strategy"
    portfolio_service_name: "portfolio_manager"
    data_handler_service_name: "data_handler"
    risk_manager_service_name: "risk_manager"
    execution_handler_service_name: "execution_handler"
    metric_to_optimize: "get_final_portfolio_value" 
    higher_metric_is_better: True

  data_handler_csv:
    csv_file_path: "data/SPY_1min.csv"
    symbol: "SPY"
    timestamp_column: "timestamp"
    train_test_split_ratio: 0.8
    # We can remove or comment out date_column and time_column from config
    # as they are not present in the CSV in that form.
    # date_column: "Date" # Not needed if using a single timestamp_column
    # time_column: "Time" # Not needed if using a single timestamp_column
    open_column: "Open"     # Ensure these match your CSV
    high_column: "High"
    low_column: "Low"
    close_column: "Close"
    volume_column: "Volume"

