# Test configuration for RegimeAdaptiveEnsembleComposed strategy with optimization workflow
# Based on test_workflow_optimization.yaml structure

# Core system configuration
logging:
  level: WARNING
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Run mode - will be overridden by --optimize flag
run_mode: backtest

# Optimization configuration with workflow
optimization:
  strategy_name: strategy
  method: grid
  metric: sharpe_ratio
  max_iterations: 100
  regime_specific: true
  regimes: ["trending_up", "trending_down", "volatile", "default"]
  # Train/test split parameters
  optimization_method: "regime_specific_with_split"
  train_ratio: 0.8
  
  # Config-driven workflow with isolated optimization
  workflow:
    # Step 1: Optimize MA crossover rule in isolation
    - name: "optimize_ma_isolated"
      type: "rulewise"
      targets: ["ma_crossover"]
      isolate: true
      method: "grid_search"
      metric: "sharpe_ratio"
      
    # Step 2: Optimize RSI rule in isolation
    - name: "optimize_rsi_isolated"
      type: "rulewise"
      targets: ["rsi"]
      isolate: true
      method: "grid_search"
      metric: "sharpe_ratio"
      
    # Step 3: Optimize Bollinger Bands rule in isolation
    - name: "optimize_bb_isolated"
      type: "rulewise"
      targets: ["bb"]
      isolate: true
      method: "grid_search"
      metric: "sharpe_ratio"
      
    # Step 4: Optimize MACD rule in isolation
    - name: "optimize_macd_isolated"
      type: "rulewise"
      targets: ["macd"]
      isolate: true
      method: "grid_search"
      metric: "sharpe_ratio"
      
    # Step 5: Optimize ensemble weights for all 4 rules
    - name: "optimize_weights"
      type: "ensemble_weights"
      method: "grid_search"
      depends_on: ["optimize_ma_isolated", "optimize_rsi_isolated", "optimize_bb_isolated", "optimize_macd_isolated"]
      weight_combinations:
        # Balanced combinations (no zeros)
        - [0.2, 0.2, 0.2, 0.4]      # MACD slightly dominant
        - [0.2, 0.2, 0.4, 0.2]      # BB slightly dominant  
        - [0.2, 0.4, 0.2, 0.2]      # RSI slightly dominant
        - [0.4, 0.2, 0.2, 0.2]      # MA slightly dominant
        
        # Single rule very dominant (>= 0.6)
        - [0.6, 0.2, 0.2, 0.0]      # MA very dominant, no MACD
        - [0.2, 0.6, 0.2, 0.0]      # RSI very dominant, no MACD
        - [0.2, 0.2, 0.6, 0.0]      # BB very dominant, no MACD
        - [0.0, 0.2, 0.2, 0.6]      # MACD very dominant, no MA
        
        # Single rule extremely dominant (>= 0.8)
        - [0.8, 0.0, 0.0, 0.2]      # MA extreme, only MACD backup
        - [0.0, 0.8, 0.2, 0.0]      # RSI extreme, only BB backup
        - [0.0, 0.0, 0.8, 0.2]      # BB extreme, only MACD backup
        - [0.2, 0.0, 0.0, 0.8]      # MACD extreme, only MA backup
        
        # Two-rule combinations
        - [0.4, 0.4, 0.2, 0.0]      # MA/RSI focused, no MACD
        - [0.4, 0.0, 0.4, 0.2]      # MA/BB focused
        - [0.0, 0.4, 0.4, 0.2]      # RSI/BB focused
        - [0.2, 0.2, 0.0, 0.6]      # MACD dominant with MA/RSI backup
        
        # Single rule only
        - [1.0, 0.0, 0.0, 0.0]      # MA only
        - [0.0, 1.0, 0.0, 0.0]      # RSI only
        - [0.0, 0.0, 1.0, 0.0]      # BB only
        - [0.0, 0.0, 0.0, 1.0]      # MACD only
      
    # Step 6: Regime-specific optimization
    - name: "regime_optimization"
      type: "regime"
      config:
        strategy_name: "strategy"
        regime_detector: "regime_detector"
        optimization_method: "grid_search"
        optimization_metric: "sharpe_ratio"

# Component configurations
components:
  # Event bus
  event_bus:
    class_path: src.core.event_bus.EventBus
    config:
      name: "main_event_bus"

  # Data handler with train/test split support
  data_handler:
    class_path: src.data.csv_data_handler.CSVDataHandler
    config:
      csv_file_path: "data/SPY_1min.csv"
      symbol: "SPY"
      timestamp_column: "timestamp"
      # Train/test split ratio for both optimization and verification
      train_test_split_ratio: 0.8

  # Strategy configuration - the ensemble strategy
  strategy:
    class_path: src.strategy.implementations.regime_adaptive_ensemble_composed.RegimeAdaptiveEnsembleComposed
    config:
      symbol: "SPY"
      regime_params_file_path: "test_regime_parameters.json"
      fallback_to_overall_best: true
      regime_detector_name: "regime_detector"  # Filter out MyPrimaryRegimeDetector
      
      # MA indicator configuration
      ma_indicator:
        short_window: 10
        long_window: 20
        
      # RSI indicator configuration  
      rsi_indicator:
        period: 14
        
      # Bollinger Bands indicator configuration
      bb_indicator:
        enabled: true
        period: 20
        num_std_dev: 2.0
        
      # MACD indicator configuration
      macd_indicator:
        enabled: true
        fast_period: 12
        slow_period: 26
        signal_period: 9
        
      # MA rule configuration
      ma_rule:
        weight: 0.25
        
      # RSI rule configuration
      rsi_rule:
        oversold_threshold: 30.0
        overbought_threshold: 70.0
        weight: 0.25
        
      # Bollinger Bands rule configuration
      bb_rule:
        enabled: true
        weight: 0.25
        band_width_filter: 0.0
        
      # MACD rule configuration
      macd_rule:
        enabled: true
        weight: 0.25
        signal_threshold: 0.0
  
  # Optimizer entry point
  optimizer:
    class_path: src.execution.optimization_entrypoint.OptimizationEntrypoint
    config:
      strategy_name: strategy
      method: grid
      metric: sharpe_ratio
      regime_specific: true
      optimization_method: "regime_specific_with_split"
      train_ratio: 0.8
      regimes: ["trending_up", "trending_down", "volatile", "default"]
  
  # Workflow orchestrator component
  workflow_orchestrator:
    class_path: src.strategy.optimization.workflow_orchestrator.OptimizationWorkflowOrchestrator
    config:
      # Config is in optimization.workflow section above

  # Regime detector with indicators
  regime_detector:
    class_path: src.strategy.regime_detector.RegimeDetector
    config:
      min_regime_duration: 1
      indicators:
        ma_trend:
          type: simple_ma_trend
          parameters:
            short_period: 10
            long_period: 30
        rsi:
          type: rsi
          parameters:
            period: 14
        atr:
          type: atr
          parameters:
            period: 14
      regime_thresholds:
        trending_up:
          ma_trend:
            min: 0.01
          rsi:
            min: 55
            max: 80
        trending_down:
          ma_trend:
            max: -0.01
          rsi:
            min: 20
            max: 45
        volatile:
          atr:
            min: 0.5
        default:
          priority: 0

  # Risk management
  risk_manager:
    class_path: src.risk.basic_risk_manager.BasicRiskManager
    config:
      max_position_size: 100
      stop_loss_pct: 0.02

  # Portfolio management
  portfolio_manager:
    class_path: src.risk.basic_portfolio.BasicPortfolio
    config:
      initial_cash: 100000
      max_positions: 1

  # Execution handler
  execution_handler:
    class_path: src.execution.simulated_execution_handler.SimulatedExecutionHandler
    config:
      latency_ms: 10

  # Backtest runner
  backtest_runner:
    class_path: src.execution.backtest_runner.BacktestRunner
    config:
      start_date: "2024-01-01"
      end_date: "2024-12-31"
      # use_test_dataset is controlled by --dataset CLI flag